basePath: /pos/v1
consumes:
- application/json
definitions:
  PurchasePayload:
    description: Detailed information regarding a POS purchase operation
    example:
      id: ""
      locator: MPOS00123820-UAT-A02
      purchase_value: 119.99
    properties:
      id:
        example: ""
        type: string
      locator:
        description: Operation reference code
        example: MPOS00123820-UAT-A02
        maxLength: 30
        minLength: 1
        type: string
      purchase_value:
        description: Total amount paid
        example: 119.99
        minimum: 0.01
        type: number
    required:
    - locator
    - purchase_value
    title: PurchasePayload
    type: object
  error:
    description: Error response media type (default view)
    example:
      code: invalid_value
      detail: Value of ID must be an integer
      id: 3F1FKVRR
      meta:
        timestamp: 1.458609e+09
      status: "400"
    properties:
      code:
        description: an application-specific error code, expressed as a string value.
        example: invalid_value
        type: string
      detail:
        description: a human-readable explanation specific to this occurrence of the
          problem.
        example: Value of ID must be an integer
        type: string
      id:
        description: a unique identifier for this particular occurrence of the problem.
        example: 3F1FKVRR
        type: string
      meta:
        additionalProperties: true
        description: a meta object containing non-standard meta-information about
          the error.
        example:
          timestamp: 1.458609e+09
        type: object
      status:
        description: the HTTP status code applicable to this problem, expressed as
          a string value.
        example: "400"
        type: string
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
host: localhost:5001
info:
  contact:
    name: psavelis
    url: https://github.com/psavelis
  description: point of sale microservice
  license:
    name: GPL-3.0
    url: https://github.com/psavelis/goa-pos-poc/blob/master/LICENSE
  title: Point Of Sale (POS)
  version: v1
paths:
  /purchases/:
    post:
      description: creates a purchase
      operationId: Purchase#create
      parameters:
      - description: Detailed information regarding a POS purchase operation
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/PurchasePayload'
      produces:
      - application/vnd.goa.error
      - application/vnd.goa.error
      responses:
        "201":
          description: Resource created
          headers:
            Location:
              description: href to created resource
              pattern: ^/purchases/[A-Za-z0-9_.]+$
              type: string
        "400":
          description: Bad Request
        "409":
          description: A conflict arose from your request. (e.g. resource already
            exists)
          headers:
            X-Request-Id:
              pattern: '[a-f0-9]+'
              type: string
      schemes:
      - http
      summary: create Purchase
      tags:
      - Purchase
  /purchases/{transaction_id}:
    get:
      description: retrieves a purchase
      operationId: Purchase#show
      parameters:
      - description: Unique transaction identifier
        in: path
        name: transaction_id
        pattern: ^[0-9a-fA-F]{24}$
        required: true
        type: string
      produces:
      - application/vnd.goa.error
      - application/vnd.goa.error
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/error'
        "400":
          description: Bad Request
        "404":
          description: Not Found
      schemes:
      - http
      summary: show Purchase
      tags:
      - Purchase
produces:
- application/json
responses:
  Conflict:
    description: A conflict arose from your request. (e.g. resource already exists)
    headers:
      X-Request-Id:
        pattern: '[a-f0-9]+'
        type: string
schemes:
- http
swagger: "2.0"
