consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
definitions:
  Purchase:
    description: Purchase media type (default view)
    example:
      Locator: 0phtqs7
      PurchaseValue: 0.017967071
      TransactionId: Id mollitia deleniti rem rerum fugiat.
    properties:
      Locator:
        description: Operation reference code
        example: 0phtqs7
        maxLength: 30
        minLength: 1
        type: string
      PurchaseValue:
        description: Total amount paid
        example: 0.017967071
        minimum: 0.01
        type: number
      TransactionId:
        description: Unique transaction identifier
        example: Id mollitia deleniti rem rerum fugiat.
        type: string
    required:
    - TransactionId
    - Locator
    - PurchaseValue
    title: 'Mediatype identifier: application/vnd.pos-purchases+json; view=default'
    type: object
  PurchasePayload:
    description: Detailed information regarding a POS purchase operation
    example:
      Locator: "y"
      PurchaseValue: 0.010328093
    properties:
      Locator:
        description: Operation reference code
        example: "y"
        maxLength: 30
        minLength: 1
        type: string
      PurchaseValue:
        description: Total amount paid
        example: 0.010328093
        minimum: 0.01
        type: number
    required:
    - Locator
    - PurchaseValue
    title: PurchasePayload
    type: object
  error:
    description: Error response media type (default view)
    example:
      code: invalid_value
      detail: Value of ID must be an integer
      id: 3F1FKVRR
      meta:
        timestamp: 1.458609e+09
      status: "400"
    properties:
      code:
        description: an application-specific error code, expressed as a string value.
        example: invalid_value
        type: string
      detail:
        description: a human-readable explanation specific to this occurrence of the
          problem.
        example: Value of ID must be an integer
        type: string
      id:
        description: a unique identifier for this particular occurrence of the problem.
        example: 3F1FKVRR
        type: string
      meta:
        additionalProperties: true
        description: a meta object containing non-standard meta-information about
          the error.
        example:
          timestamp: 1.458609e+09
        type: object
      status:
        description: the HTTP status code applicable to this problem, expressed as
          a string value.
        example: "400"
        type: string
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
host: localhost:5001
info:
  description: point of sale microservice
  title: Point Of Sale API
  version: v1
paths:
  /purchases/:
    post:
      description: creates a purchase
      operationId: Purchase#create
      parameters:
      - description: Detailed information regarding a POS purchase operation
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/PurchasePayload'
      responses:
        "201":
          description: Created
      summary: create Purchase
      tags:
      - Purchase
  /purchases/{TransactionId}:
    get:
      description: retrieve an specific purchase
      operationId: Purchase#find
      parameters:
      - in: path
        name: TransactionId
        required: true
        type: string
      produces:
      - application/vnd.pos-purchases+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Purchase'
      summary: find Purchase
      tags:
      - Purchase
  /swagger.json:
    get:
      operationId: Swagger#/swagger.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      summary: Download swagger/swagger.json
  /swagger/{filepath}:
    get:
      operationId: Swagger#/swagger/*filepath
      parameters:
      - description: Relative file path
        in: path
        name: filepath
        required: true
        type: string
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
        "404":
          description: File not found
          schema:
            $ref: '#/definitions/error'
      summary: Download swagger
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
responses:
  Created:
    description: Created
swagger: "2.0"
