// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "pos": Application Controllers
//
// Command:
// $ goagen
// --design=github.com/psavelis/goa-pos-poc/design
// --out=$(GOPATH)src\github.com\psavelis\goa-pos-poc
// --version=v1.3.0

package app

import (
	"context"
	"github.com/goadesign/goa"
	"net/http"
)

// initService sets up the service encoders, decoders and mux.
func initService(service *goa.Service) {
	// Setup encoders and decoders
	service.Encoder.Register(goa.NewJSONEncoder, "application/json")
	service.Encoder.Register(goa.NewGobEncoder, "application/gob", "application/x-gob")
	service.Encoder.Register(goa.NewXMLEncoder, "application/xml")
	service.Decoder.Register(goa.NewJSONDecoder, "application/json")
	service.Decoder.Register(goa.NewGobDecoder, "application/gob", "application/x-gob")
	service.Decoder.Register(goa.NewXMLDecoder, "application/xml")

	// Setup default encoder and decoder
	service.Encoder.Register(goa.NewJSONEncoder, "*/*")
	service.Decoder.Register(goa.NewJSONDecoder, "*/*")
}

// PurchaseController is the controller interface for the Purchase actions.
type PurchaseController interface {
	goa.Muxer
	Create(*CreatePurchaseContext) error
	Find(*FindPurchaseContext) error
}

// MountPurchaseController "mounts" a Purchase resource controller on the given service.
func MountPurchaseController(service *goa.Service, ctrl PurchaseController) {
	initService(service)
	var h goa.Handler

	h = func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		// Check if there was an error loading the request
		if err := goa.ContextError(ctx); err != nil {
			return err
		}
		// Build the context
		rctx, err := NewCreatePurchaseContext(ctx, req, service)
		if err != nil {
			return err
		}
		// Build the payload
		if rawPayload := goa.ContextRequest(ctx).Payload; rawPayload != nil {
			rctx.Payload = rawPayload.(*PurchasePayload)
		} else {
			return goa.MissingPayloadError()
		}
		return ctrl.Create(rctx)
	}
	service.Mux.Handle("POST", "/purchases/", ctrl.MuxHandler("create", h, unmarshalCreatePurchasePayload))
	service.LogInfo("mount", "ctrl", "Purchase", "action", "Create", "route", "POST /purchases/")

	h = func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		// Check if there was an error loading the request
		if err := goa.ContextError(ctx); err != nil {
			return err
		}
		// Build the context
		rctx, err := NewFindPurchaseContext(ctx, req, service)
		if err != nil {
			return err
		}
		return ctrl.Find(rctx)
	}
	service.Mux.Handle("GET", "/purchases/:TransactionId", ctrl.MuxHandler("find", h, nil))
	service.LogInfo("mount", "ctrl", "Purchase", "action", "Find", "route", "GET /purchases/:TransactionId")
}

// unmarshalCreatePurchasePayload unmarshals the request body into the context request data Payload field.
func unmarshalCreatePurchasePayload(ctx context.Context, service *goa.Service, req *http.Request) error {
	payload := &purchasePayload{}
	if err := service.DecodeRequest(req, payload); err != nil {
		return err
	}
	if err := payload.Validate(); err != nil {
		// Initialize payload with private data structure so it can be logged
		goa.ContextRequest(ctx).Payload = payload
		return err
	}
	goa.ContextRequest(ctx).Payload = payload.Publicize()
	return nil
}
