// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "pos": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/psavelis/goa-pos-poc/design
// --out=$(GOPATH)src\github.com\psavelis\goa-pos-poc
// --version=v1.3.0

package app

import (
	"fmt"
	"strings"
)

// PurchaseHref returns the resource href.
func PurchaseHref(transactionID interface{}) string {
	paramtransactionID := strings.TrimLeftFunc(fmt.Sprintf("%v", transactionID), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/purchases/%v", paramtransactionID)
}
