// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "pos": Application User Types
//
// Command:
// $ goagen
// --design=github.com/psavelis/goa-pos-poc/design
// --out=c:\code\src\github.com\psavelis\goa-pos-poc
// --version=v1.3.0

package app

import (
	"github.com/goadesign/goa"
	"unicode/utf8"
)

// Detailed information regarding a POS purchase operation
type purchasePayload struct {
	// Operation reference code
	Locator *string `form:"Locator,omitempty" json:"Locator,omitempty" xml:"Locator,omitempty"`
	// Total amount paid
	PurchaseValue *float64 `form:"PurchaseValue,omitempty" json:"PurchaseValue,omitempty" xml:"PurchaseValue,omitempty"`
}

// Validate validates the purchasePayload type instance.
func (ut *purchasePayload) Validate() (err error) {
	if ut.Locator == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`request`, "Locator"))
	}
	if ut.PurchaseValue == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`request`, "PurchaseValue"))
	}
	if ut.Locator != nil {
		if utf8.RuneCountInString(*ut.Locator) < 1 {
			err = goa.MergeErrors(err, goa.InvalidLengthError(`request.Locator`, *ut.Locator, utf8.RuneCountInString(*ut.Locator), 1, true))
		}
	}
	if ut.Locator != nil {
		if utf8.RuneCountInString(*ut.Locator) > 30 {
			err = goa.MergeErrors(err, goa.InvalidLengthError(`request.Locator`, *ut.Locator, utf8.RuneCountInString(*ut.Locator), 30, false))
		}
	}
	if ut.PurchaseValue != nil {
		if *ut.PurchaseValue < 0.010000 {
			err = goa.MergeErrors(err, goa.InvalidRangeError(`request.PurchaseValue`, *ut.PurchaseValue, 0.010000, true))
		}
	}
	return
}

// Publicize creates PurchasePayload from purchasePayload
func (ut *purchasePayload) Publicize() *PurchasePayload {
	var pub PurchasePayload
	if ut.Locator != nil {
		pub.Locator = *ut.Locator
	}
	if ut.PurchaseValue != nil {
		pub.PurchaseValue = *ut.PurchaseValue
	}
	return &pub
}

// Detailed information regarding a POS purchase operation
type PurchasePayload struct {
	// Operation reference code
	Locator string `form:"Locator" json:"Locator" xml:"Locator"`
	// Total amount paid
	PurchaseValue float64 `form:"PurchaseValue" json:"PurchaseValue" xml:"PurchaseValue"`
}

// Validate validates the PurchasePayload type instance.
func (ut *PurchasePayload) Validate() (err error) {
	if ut.Locator == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`type`, "Locator"))
	}

	if utf8.RuneCountInString(ut.Locator) < 1 {
		err = goa.MergeErrors(err, goa.InvalidLengthError(`type.Locator`, ut.Locator, utf8.RuneCountInString(ut.Locator), 1, true))
	}
	if utf8.RuneCountInString(ut.Locator) > 30 {
		err = goa.MergeErrors(err, goa.InvalidLengthError(`type.Locator`, ut.Locator, utf8.RuneCountInString(ut.Locator), 30, false))
	}
	if ut.PurchaseValue < 0.010000 {
		err = goa.MergeErrors(err, goa.InvalidRangeError(`type.PurchaseValue`, ut.PurchaseValue, 0.010000, true))
	}
	return
}
