basePath: /pos/v1
consumes:
- application/json
definitions:
  Purchase:
    description: Purchase media type (default view)
    example:
      href: /pos/v1/purchases/5a06839d42e6552b004a7e03
      locator: MPOS00123820-UAT-A02
      purchase_value: 119.99
      transaction_id: 79B29Ecb61EC9F7d59ab7b77
    properties:
      href:
        description: API href of Purchase
        example: /pos/v1/purchases/5a06839d42e6552b004a7e03
        type: string
      locator:
        description: Operation reference code
        example: MPOS00123820-UAT-A02
        maxLength: 30
        minLength: 1
        type: string
      purchase_value:
        description: Total amount paid
        example: 119.99
        minimum: 0.01
        type: number
      transaction_id:
        description: Unique transaction identifier
        example: 79B29Ecb61EC9F7d59ab7b77
        pattern: ^[0-9a-fA-F]{24}$
        type: string
    required:
    - transaction_id
    - locator
    - purchase_value
    - href
    title: 'Mediatype identifier: application/json; view=default'
    type: object
  PurchasePayload:
    description: Detailed information regarding a POS purchase operation
    example:
      id: ""
      locator: MPOS00123820-UAT-A02
      purchase_value: 119.99
    properties:
      id:
        example: ""
        type: string
      locator:
        description: Operation reference code
        example: MPOS00123820-UAT-A02
        maxLength: 30
        minLength: 1
        type: string
      purchase_value:
        description: Total amount paid
        example: 119.99
        minimum: 0.01
        type: number
    required:
    - locator
    - purchase_value
    title: PurchasePayload
    type: object
host: psavelis.herokuapp.com
info:
  description: go microservice
  license:
    name: GPL-3.0
    url: https://github.com/psavelis/goa-pos-poc/blob/master/LICENSE
  title: Point Of Sale (POS)
  version: v1
paths:
  /purchases/:
    post:
      description: creates a purchase
      operationId: Purchase#create
      parameters:
      - description: Detailed information regarding a POS purchase operation
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/PurchasePayload'
      responses:
        "201":
          description: Resource created
          headers:
            Location:
              description: href to created resource
              pattern: ^/purchases/[A-Za-z0-9_.]+$
              type: string
        "400":
          description: Bad Request
        "409":
          description: A conflict arose from your request. (e.g. resource already
            exists)
          headers:
            X-Request-Id:
              pattern: '[a-f0-9]+'
              type: string
      schemes:
      - https
      summary: create Purchase
      tags:
      - Purchase
  /purchases/{transaction_id}:
    get:
      description: retrieves a purchase
      operationId: Purchase#show
      parameters:
      - description: Unique transaction identifier
        in: path
        name: transaction_id
        pattern: ^[0-9a-fA-F]{24}$
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Purchase'
        "400":
          description: Bad Request
        "404":
          description: Not Found
      schemes:
      - https
      summary: show Purchase
      tags:
      - Purchase
produces:
- application/json
responses:
  BadRequest:
    description: Bad Request
  Conflict:
    description: A conflict arose from your request. (e.g. resource already exists)
    headers:
      X-Request-Id:
        pattern: '[a-f0-9]+'
        type: string
  NotFound:
    description: Not Found
schemes:
- https
swagger: "2.0"
